/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BranchingModelDevelopment {
    #[serde(rename = "branch", skip_serializing_if = "Option::is_none")]
    pub branch: Option<Box<models::Branch>>,
    /// Name of the target branch. Will be listed here even when the target branch does not exist. Will be `null` if targeting the main branch and the repository is empty.
    #[serde(rename = "name")]
    pub name: String,
    /// Indicates if the setting points at an explicit branch (`false`) or tracks the main branch (`true`).
    #[serde(rename = "use_mainbranch")]
    pub use_mainbranch: bool,
}

impl BranchingModelDevelopment {
    pub fn new(name: String, use_mainbranch: bool) -> BranchingModelDevelopment {
        BranchingModelDevelopment {
            branch: None,
            name,
            use_mainbranch,
        }
    }
}

