/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BranchingModelSettingsBranchTypes {
    /// Whether the branch type is enabled or not. A disabled branch type may contain an invalid `prefix`.
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// The kind of the branch type.
    #[serde(rename = "kind")]
    pub kind: Kind,
    /// The prefix for this branch type. A branch with this prefix will be classified as per `kind`. The `prefix` of an enabled branch type must be a valid branch prefix.Additionally, it cannot be blank, empty or `null`. The `prefix` for a disabled branch type can be empty or invalid.
    #[serde(rename = "prefix", skip_serializing_if = "Option::is_none")]
    pub prefix: Option<String>,
}

impl BranchingModelSettingsBranchTypes {
    pub fn new(kind: Kind) -> BranchingModelSettingsBranchTypes {
        BranchingModelSettingsBranchTypes {
            enabled: None,
            kind,
            prefix: None,
        }
    }
}
/// The kind of the branch type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "feature")]
    Feature,
    #[serde(rename = "bugfix")]
    Bugfix,
    #[serde(rename = "release")]
    Release,
    #[serde(rename = "hotfix")]
    Hotfix,
}

impl Default for Kind {
    fn default() -> Kind {
        Self::Feature
    }
}

