/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BranchingModelSettings {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Box<models::BranchingModelSettingsLinks>>,
    #[serde(rename = "branch_types", skip_serializing_if = "Option::is_none")]
    pub branch_types: Option<Vec<models::BranchingModelSettingsBranchTypes>>,
    #[serde(rename = "development", skip_serializing_if = "Option::is_none")]
    pub development: Option<Box<models::BranchingModelSettingsDevelopment>>,
    #[serde(rename = "production", skip_serializing_if = "Option::is_none")]
    pub production: Option<Box<models::BranchingModelSettingsProduction>>,
}

impl BranchingModelSettings {
    pub fn new() -> BranchingModelSettings {
        BranchingModelSettings {
            r#type: None,
            links: None,
            branch_types: None,
            development: None,
            production: None,
        }
    }
}

