/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommentInline {
    /// The comment's anchor line in the old version of the file. If the comment is a multi-line comment, this is the ending line number in the old version of the file.
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<i32>,
    /// The comment's anchor line in the new version of the file. If the comment is a multi-line comment, this is the ending line number in the new version of the file.
    #[serde(rename = "to", skip_serializing_if = "Option::is_none")]
    pub to: Option<i32>,
    /// The starting line number in the old version of the file, if the comment is a multi-line comment. This is null otherwise.
    #[serde(rename = "start_from", skip_serializing_if = "Option::is_none")]
    pub start_from: Option<i32>,
    /// The starting line number in the new version of the file, if the comment is a multi-line comment. This is null otherwise.
    #[serde(rename = "start_to", skip_serializing_if = "Option::is_none")]
    pub start_to: Option<i32>,
    /// The path of the file this comment is anchored to.
    #[serde(rename = "path")]
    pub path: String,
}

impl CommentInline {
    pub fn new(path: String) -> CommentInline {
        CommentInline {
            from: None,
            to: None,
            start_from: None,
            start_to: None,
            path,
        }
    }
}

