/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommentContent {
    /// The text as it was typed by a user.
    #[serde(rename = "raw", skip_serializing_if = "Option::is_none")]
    pub raw: Option<String>,
    /// The type of markup language the raw content is to be interpreted in.
    #[serde(rename = "markup", skip_serializing_if = "Option::is_none")]
    pub markup: Option<Markup>,
    /// The user's content rendered as HTML.
    #[serde(rename = "html", skip_serializing_if = "Option::is_none")]
    pub html: Option<String>,
}

impl CommentContent {
    pub fn new() -> CommentContent {
        CommentContent {
            raw: None,
            markup: None,
            html: None,
        }
    }
}
/// The type of markup language the raw content is to be interpreted in.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Markup {
    #[serde(rename = "markdown")]
    Markdown,
    #[serde(rename = "creole")]
    Creole,
    #[serde(rename = "plaintext")]
    Plaintext,
}

impl Default for Markup {
    fn default() -> Markup {
        Self::Markdown
    }
}

