/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FileConflict : A file conflict object.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileConflict {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(rename = "scenario", skip_serializing_if = "Option::is_none")]
    pub scenario: Option<Scenario>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl FileConflict {
    /// A file conflict object.
    pub fn new(r#type: String) -> FileConflict {
        FileConflict {
            r#type,
            path: None,
            scenario: None,
            message: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Scenario {
    #[serde(rename = "delete_modify")]
    DeleteModify,
    #[serde(rename = "modify_delete")]
    ModifyDelete,
    #[serde(rename = "content")]
    Content,
    #[serde(rename = "binary")]
    Binary,
    #[serde(rename = "flags")]
    Flags,
    #[serde(rename = "mode")]
    Mode,
    #[serde(rename = "type")]
    Type,
    #[serde(rename = "symlink")]
    Symlink,
    #[serde(rename = "directory_file")]
    DirectoryFile,
    #[serde(rename = "file_directory")]
    FileDirectory,
    #[serde(rename = "add_rename")]
    AddRename,
    #[serde(rename = "rename_add")]
    RenameAdd,
    #[serde(rename = "delete_rename")]
    DeleteRename,
    #[serde(rename = "rename_delete")]
    RenameDelete,
    #[serde(rename = "rename")]
    Rename,
    #[serde(rename = "subrepo")]
    Subrepo,
    #[serde(rename = "unknown")]
    Unknown,
}

impl Default for Scenario {
    fn default() -> Scenario {
        Self::DeleteModify
    }
}

