/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssueChangeChangesAssignee {
    #[serde(rename = "old", skip_serializing_if = "Option::is_none")]
    pub old: Option<String>,
    #[serde(rename = "new", skip_serializing_if = "Option::is_none")]
    pub new: Option<String>,
}

impl IssueChangeChangesAssignee {
    pub fn new() -> IssueChangeChangesAssignee {
        IssueChangeChangesAssignee {
            old: None,
            new: None,
        }
    }
}

