/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssueLinks {
    #[serde(rename = "self", skip_serializing_if = "Option::is_none")]
    pub param_self: Option<Box<models::Link1>>,
    #[serde(rename = "html", skip_serializing_if = "Option::is_none")]
    pub html: Option<Box<models::Link1>>,
    #[serde(rename = "comments", skip_serializing_if = "Option::is_none")]
    pub comments: Option<Box<models::Link1>>,
    #[serde(rename = "attachments", skip_serializing_if = "Option::is_none")]
    pub attachments: Option<Box<models::Link1>>,
    #[serde(rename = "watch", skip_serializing_if = "Option::is_none")]
    pub watch: Option<Box<models::Link1>>,
    #[serde(rename = "vote", skip_serializing_if = "Option::is_none")]
    pub vote: Option<Box<models::Link1>>,
}

impl IssueLinks {
    pub fn new() -> IssueLinks {
        IssueLinks {
            param_self: None,
            html: None,
            comments: None,
            attachments: None,
            watch: None,
            vote: None,
        }
    }
}

