/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PipelineCommitTarget {
    #[serde(rename = "commit", skip_serializing_if = "Option::is_none")]
    pub commit: Option<Box<models::Commit>>,
    #[serde(rename = "selector", skip_serializing_if = "Option::is_none")]
    pub selector: Option<Box<models::PipelineSelector>>,
    /// Type discriminator for pipeline_commit_target
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
}

impl PipelineCommitTarget {
    pub fn new() -> PipelineCommitTarget {
        PipelineCommitTarget {
            commit: None,
            selector: None,
            r#type: None,
        }
    }
}
/// Type discriminator for pipeline_commit_target
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "pipeline_commit_target")]
    PipelineCommitTarget,
}

impl Default for Type {
    fn default() -> Type {
        Self::PipelineCommitTarget
    }
}

