/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PipelineStateInProgress {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// The name of pipeline state (IN_PROGRESS).
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<Name>,
    #[serde(rename = "stage", skip_serializing_if = "Option::is_none")]
    pub stage: Option<Box<models::PipelineStateInProgressStage>>,
}

impl PipelineStateInProgress {
    pub fn new() -> PipelineStateInProgress {
        PipelineStateInProgress {
            r#type: None,
            name: None,
            stage: None,
        }
    }
}
/// The name of pipeline state (IN_PROGRESS).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Name {
    #[serde(rename = "IN_PROGRESS")]
    InProgress,
}

impl Default for Name {
    fn default() -> Name {
        Self::InProgress
    }
}

