/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PipelineRunner {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// The UUID identifying the runner.
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
    /// The name of the runner.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Labels assigned to the runner for identification and routing.
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<Vec<String>>,
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<Box<models::PipelineRunnerState>>,
    /// The timestamp when the runner was created.
    #[serde(rename = "created_on", skip_serializing_if = "Option::is_none")]
    pub created_on: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// The timestamp when the runner was last updated.
    #[serde(rename = "updated_on", skip_serializing_if = "Option::is_none")]
    pub updated_on: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "oauth_client", skip_serializing_if = "Option::is_none")]
    pub oauth_client: Option<Box<models::PipelineRunnerOauthClient>>,
}

impl PipelineRunner {
    pub fn new() -> PipelineRunner {
        PipelineRunner {
            r#type: None,
            uuid: None,
            name: None,
            labels: None,
            state: None,
            created_on: None,
            updated_on: None,
            oauth_client: None,
        }
    }
}

