/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum PipelineTarget {
    #[serde(rename="pipeline_ref_target")]
    PipelineRefTarget(models::PipelineRefTarget),
    #[serde(rename="pipeline_commit_target")]
    PipelineCommitTarget(models::PipelineCommitTarget),
    #[serde(rename="pipeline_pullrequest_target")]
    PipelinePullrequestTarget(models::PipelinePullrequestTarget),
}

impl Default for PipelineTarget {
    fn default() -> Self {
        Self::PipelineRefTarget(Default::default())
    }
}

/// The type of reference (branch/tag).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RefType {
    #[serde(rename = "branch")]
    Branch,
    #[serde(rename = "tag")]
    Tag,
    #[serde(rename = "named_branch")]
    NamedBranch,
    #[serde(rename = "bookmark")]
    Bookmark,
}

impl Default for RefType {
    fn default() -> RefType {
        Self::Branch
    }
}

