/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PipelineSchedule {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// The UUID identifying the schedule.
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
    /// Whether the schedule is enabled.
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
    pub target: Option<models::PipelineRefTarget>,
    /// The cron expression with second precision (7 fields) that the schedule applies. For example, for expression: 0 0 12 * * ? *, will execute at 12pm UTC every day.
    #[serde(rename = "cron_pattern", skip_serializing_if = "Option::is_none")]
    pub cron_pattern: Option<String>,
    /// The timestamp when the schedule was created.
    #[serde(rename = "created_on", skip_serializing_if = "Option::is_none")]
    pub created_on: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// The timestamp when the schedule was updated.
    #[serde(rename = "updated_on", skip_serializing_if = "Option::is_none")]
    pub updated_on: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl PipelineSchedule {
    pub fn new() -> PipelineSchedule {
        PipelineSchedule {
            r#type: None,
            uuid: None,
            enabled: None,
            target: None,
            cron_pattern: None,
            created_on: None,
            updated_on: None,
        }
    }
}

