/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PipelinePullrequestTarget : A pipeline pull request target (placeholder - not fully documented in spec)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PipelinePullrequestTarget {
    /// Type discriminator for pipeline_pullrequest_target
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
}

impl PipelinePullrequestTarget {
    /// A pipeline pull request target (placeholder - not fully documented in spec)
    pub fn new() -> PipelinePullrequestTarget {
        PipelinePullrequestTarget {
            r#type: None,
        }
    }
}
/// Type discriminator for pipeline_pullrequest_target
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "pipeline_pullrequest_target")]
    PipelinePullrequestTarget,
}

impl Default for Type {
    fn default() -> Type {
        Self::PipelinePullrequestTarget
    }
}

