/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PipelineRefTarget {
    /// The type of reference (branch/tag).
    #[serde(rename = "ref_type", skip_serializing_if = "Option::is_none")]
    pub ref_type: Option<RefType>,
    /// The name of the reference.
    #[serde(rename = "ref_name", skip_serializing_if = "Option::is_none")]
    pub ref_name: Option<String>,
    #[serde(rename = "commit", skip_serializing_if = "Option::is_none")]
    pub commit: Option<Box<models::Commit>>,
    #[serde(rename = "selector", skip_serializing_if = "Option::is_none")]
    pub selector: Option<Box<models::PipelineSelector>>,
    /// Type discriminator for pipeline_ref_target
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
}

impl PipelineRefTarget {
    pub fn new() -> PipelineRefTarget {
        PipelineRefTarget {
            ref_type: None,
            ref_name: None,
            commit: None,
            selector: None,
            r#type: None,
        }
    }
}
/// The type of reference (branch/tag).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RefType {
    #[serde(rename = "branch")]
    Branch,
    #[serde(rename = "tag")]
    Tag,
    #[serde(rename = "named_branch")]
    NamedBranch,
    #[serde(rename = "bookmark")]
    Bookmark,
}

impl Default for RefType {
    fn default() -> RefType {
        Self::Branch
    }
}
/// Type discriminator for pipeline_ref_target
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "pipeline_ref_target")]
    PipelineRefTarget,
}

impl Default for Type {
    fn default() -> Type {
        Self::PipelineRefTarget
    }
}

