/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum PipelineTrigger {
    #[serde(rename="pipeline_trigger_manual")]
    PipelineTriggerManual {
        /// The name of the trigger (e.g., PUSH for push triggers, MANUAL for manual triggers)
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
    },
    #[serde(rename="pipeline_trigger_push")]
    PipelineTriggerPush {
        /// The name of the trigger (e.g., PUSH for push triggers, MANUAL for manual triggers)
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
    },
}

impl Default for PipelineTrigger {
    fn default() -> Self {
        Self::PipelineTriggerManual {
            name: Default::default(),
        }
        
    }
}


