/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum PipelineTarget {
    #[serde(rename="pipeline_commit_target")]
    PipelineCommitTarget {
    },
    #[serde(rename="pipeline_ref_target")]
    PipelineRefTarget {
    },
}

impl Default for PipelineTarget {
    fn default() -> Self {
        Self::PipelineCommitTarget {
        }
        
    }
}


