/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum PipelineRefTarget {
    #[serde(rename="pipeline_commit_target")]
    PipelineCommitTarget {
        /// The type of reference (branch/tag).
        #[serde(rename = "ref_type", skip_serializing_if = "Option::is_none")]
        ref_type: Option<RefType>,
        /// The name of the reference.
        #[serde(rename = "ref_name", skip_serializing_if = "Option::is_none")]
        ref_name: Option<String>,
        #[serde(rename = "commit", skip_serializing_if = "Option::is_none")]
        commit: Option<Box<models::Commit>>,
        #[serde(rename = "selector", skip_serializing_if = "Option::is_none")]
        selector: Option<Box<models::PipelineSelector>>,
    },
    #[serde(rename="pipeline_ref_target")]
    PipelineRefTarget {
        /// The type of reference (branch/tag).
        #[serde(rename = "ref_type", skip_serializing_if = "Option::is_none")]
        ref_type: Option<RefType>,
        /// The name of the reference.
        #[serde(rename = "ref_name", skip_serializing_if = "Option::is_none")]
        ref_name: Option<String>,
        #[serde(rename = "commit", skip_serializing_if = "Option::is_none")]
        commit: Option<Box<models::Commit>>,
        #[serde(rename = "selector", skip_serializing_if = "Option::is_none")]
        selector: Option<Box<models::PipelineSelector>>,
    },
}

impl Default for PipelineRefTarget {
    fn default() -> Self {
        Self::PipelineCommitTarget {
            ref_type: Default::default(),
            ref_name: Default::default(),
            commit: Default::default(),
            selector: Default::default(),
        }
        
    }
}

/// The type of reference (branch/tag).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RefType {
    #[serde(rename = "branch")]
    Branch,
    #[serde(rename = "tag")]
    Tag,
    #[serde(rename = "named_branch")]
    NamedBranch,
    #[serde(rename = "bookmark")]
    Bookmark,
}

impl Default for RefType {
    fn default() -> RefType {
        Self::Branch
    }
}

