/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum PipelineCommitTarget {
    #[serde(rename="pipeline_commit_target")]
    PipelineCommitTarget {
        #[serde(rename = "commit", skip_serializing_if = "Option::is_none")]
        commit: Option<Box<models::Commit>>,
        #[serde(rename = "selector", skip_serializing_if = "Option::is_none")]
        selector: Option<Box<models::PipelineSelector>>,
    },
    #[serde(rename="pipeline_ref_target")]
    PipelineRefTarget {
        #[serde(rename = "commit", skip_serializing_if = "Option::is_none")]
        commit: Option<Box<models::Commit>>,
        #[serde(rename = "selector", skip_serializing_if = "Option::is_none")]
        selector: Option<Box<models::PipelineSelector>>,
    },
}

impl Default for PipelineCommitTarget {
    fn default() -> Self {
        Self::PipelineCommitTarget {
            commit: Default::default(),
            selector: Default::default(),
        }
        
    }
}


