/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PipelineRunnerState {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// The current status of the runner.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<Box<models::PipelineRunnerVersion>>,
    /// The timestamp when the runner state was last updated.
    #[serde(rename = "updated_on", skip_serializing_if = "Option::is_none")]
    pub updated_on: Option<String>,
    /// Whether the runner is cordoned (prevented from accepting new steps).
    #[serde(rename = "cordoned", skip_serializing_if = "Option::is_none")]
    pub cordoned: Option<bool>,
}

impl PipelineRunnerState {
    pub fn new() -> PipelineRunnerState {
        PipelineRunnerState {
            r#type: None,
            status: None,
            version: None,
            updated_on: None,
            cordoned: None,
        }
    }
}
/// The current status of the runner.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "UNREGISTERED")]
    Unregistered,
    #[serde(rename = "ONLINE")]
    Online,
    #[serde(rename = "OFFLINE")]
    Offline,
    #[serde(rename = "DISABLED")]
    Disabled,
    #[serde(rename = "ENABLED")]
    Enabled,
    #[serde(rename = "UNHEALTHY")]
    Unhealthy,
}

impl Default for Status {
    fn default() -> Status {
        Self::Unregistered
    }
}

