/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectBranchingModelBranchTypes {
    /// The kind of branch.
    #[serde(rename = "kind")]
    pub kind: Kind,
    /// The prefix for this branch type. A branch with this prefix will be classified as per `kind`. The prefix must be a valid prefix for a branch and must always exist. It cannot be blank, empty or `null`.
    #[serde(rename = "prefix")]
    pub prefix: String,
}

impl ProjectBranchingModelBranchTypes {
    pub fn new(kind: Kind, prefix: String) -> ProjectBranchingModelBranchTypes {
        ProjectBranchingModelBranchTypes {
            kind,
            prefix,
        }
    }
}
/// The kind of branch.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "feature")]
    Feature,
    #[serde(rename = "bugfix")]
    Bugfix,
    #[serde(rename = "release")]
    Release,
    #[serde(rename = "hotfix")]
    Hotfix,
}

impl Default for Kind {
    fn default() -> Kind {
        Self::Feature
    }
}

