/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectBranchingModelDevelopment {
    /// Name of the target branch. If inherited by a repository, it will default to the main branch if the specified branch does not exist.
    #[serde(rename = "name")]
    pub name: String,
    /// Indicates if the setting points at an explicit branch (`false`) or tracks the main branch (`true`).
    #[serde(rename = "use_mainbranch")]
    pub use_mainbranch: bool,
}

impl ProjectBranchingModelDevelopment {
    pub fn new(name: String, use_mainbranch: bool) -> ProjectBranchingModelDevelopment {
        ProjectBranchingModelDevelopment {
            name,
            use_mainbranch,
        }
    }
}

