/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PullRequestBranch {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Available merge strategies, when this endpoint is the destination of the pull request.
    #[serde(rename = "merge_strategies", skip_serializing_if = "Option::is_none")]
    pub merge_strategies: Option<Vec<MergeStrategies>>,
    /// The default merge strategy, when this endpoint is the destination of the pull request.
    #[serde(rename = "default_merge_strategy", skip_serializing_if = "Option::is_none")]
    pub default_merge_strategy: Option<String>,
}

impl PullRequestBranch {
    pub fn new() -> PullRequestBranch {
        PullRequestBranch {
            name: None,
            merge_strategies: None,
            default_merge_strategy: None,
        }
    }
}
/// Available merge strategies, when this endpoint is the destination of the pull request.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MergeStrategies {
    #[serde(rename = "merge_commit")]
    MergeCommit,
    #[serde(rename = "squash")]
    Squash,
    #[serde(rename = "fast_forward")]
    FastForward,
    #[serde(rename = "squash_fast_forward")]
    SquashFastForward,
    #[serde(rename = "rebase_fast_forward")]
    RebaseFastForward,
    #[serde(rename = "rebase_merge")]
    RebaseMerge,
}

impl Default for MergeStrategies {
    fn default() -> MergeStrategies {
        Self::MergeCommit
    }
}

