/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PullrequestComment {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "created_on", skip_serializing_if = "Option::is_none")]
    pub created_on: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "updated_on", skip_serializing_if = "Option::is_none")]
    pub updated_on: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<Box<models::CommentContent>>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<models::Account>>,
    #[serde(rename = "deleted", skip_serializing_if = "Option::is_none")]
    pub deleted: Option<bool>,
    #[serde(rename = "parent", skip_serializing_if = "Option::is_none")]
    pub parent: Option<Box<models::Comment>>,
    #[serde(rename = "inline", skip_serializing_if = "Option::is_none")]
    pub inline: Option<Box<models::CommentInline>>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Box<models::CommentLinks>>,
    #[serde(rename = "pullrequest", skip_serializing_if = "Option::is_none")]
    pub pullrequest: Option<Box<models::Pullrequest>>,
    #[serde(rename = "resolution", skip_serializing_if = "Option::is_none")]
    pub resolution: Option<models::CommentResolution>,
    #[serde(rename = "pending", skip_serializing_if = "Option::is_none")]
    pub pending: Option<bool>,
}

impl PullrequestComment {
    pub fn new() -> PullrequestComment {
        PullrequestComment {
            r#type: None,
            id: None,
            created_on: None,
            updated_on: None,
            content: None,
            user: None,
            deleted: None,
            parent: None,
            inline: None,
            links: None,
            pullrequest: None,
            resolution: None,
            pending: None,
        }
    }
}

