/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PullRequestLinks {
    #[serde(rename = "self", skip_serializing_if = "Option::is_none")]
    pub param_self: Option<Box<models::Link1>>,
    #[serde(rename = "html", skip_serializing_if = "Option::is_none")]
    pub html: Option<Box<models::Link1>>,
    #[serde(rename = "commits", skip_serializing_if = "Option::is_none")]
    pub commits: Option<Box<models::Link1>>,
    #[serde(rename = "approve", skip_serializing_if = "Option::is_none")]
    pub approve: Option<Box<models::Link1>>,
    #[serde(rename = "diff", skip_serializing_if = "Option::is_none")]
    pub diff: Option<Box<models::Link1>>,
    #[serde(rename = "diffstat", skip_serializing_if = "Option::is_none")]
    pub diffstat: Option<Box<models::Link1>>,
    #[serde(rename = "comments", skip_serializing_if = "Option::is_none")]
    pub comments: Option<Box<models::Link1>>,
    #[serde(rename = "activity", skip_serializing_if = "Option::is_none")]
    pub activity: Option<Box<models::Link1>>,
    #[serde(rename = "merge", skip_serializing_if = "Option::is_none")]
    pub merge: Option<Box<models::Link1>>,
    #[serde(rename = "decline", skip_serializing_if = "Option::is_none")]
    pub decline: Option<Box<models::Link1>>,
}

impl PullRequestLinks {
    pub fn new() -> PullRequestLinks {
        PullRequestLinks {
            param_self: None,
            html: None,
            commits: None,
            approve: None,
            diff: None,
            diffstat: None,
            comments: None,
            activity: None,
            merge: None,
            decline: None,
        }
    }
}

