/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RenderedPullRequestMarkup : User provided pull request text, interpreted in a markup language and rendered in HTML
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RenderedPullRequestMarkup {
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<Box<models::CommentContent>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<Box<models::CommentContent>>,
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<Box<models::CommentContent>>,
}

impl RenderedPullRequestMarkup {
    /// User provided pull request text, interpreted in a markup language and rendered in HTML
    pub fn new() -> RenderedPullRequestMarkup {
        RenderedPullRequestMarkup {
            title: None,
            description: None,
            reason: None,
        }
    }
}

