/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RepositoryLinks {
    #[serde(rename = "self", skip_serializing_if = "Option::is_none")]
    pub param_self: Option<Box<models::Link1>>,
    #[serde(rename = "html", skip_serializing_if = "Option::is_none")]
    pub html: Option<Box<models::Link1>>,
    #[serde(rename = "avatar", skip_serializing_if = "Option::is_none")]
    pub avatar: Option<Box<models::Link1>>,
    #[serde(rename = "pullrequests", skip_serializing_if = "Option::is_none")]
    pub pullrequests: Option<Box<models::Link1>>,
    #[serde(rename = "commits", skip_serializing_if = "Option::is_none")]
    pub commits: Option<Box<models::Link1>>,
    #[serde(rename = "forks", skip_serializing_if = "Option::is_none")]
    pub forks: Option<Box<models::Link1>>,
    #[serde(rename = "watchers", skip_serializing_if = "Option::is_none")]
    pub watchers: Option<Box<models::Link1>>,
    #[serde(rename = "downloads", skip_serializing_if = "Option::is_none")]
    pub downloads: Option<Box<models::Link1>>,
    #[serde(rename = "clone", skip_serializing_if = "Option::is_none")]
    pub clone: Option<Vec<models::Link1>>,
    #[serde(rename = "hooks", skip_serializing_if = "Option::is_none")]
    pub hooks: Option<Box<models::Link1>>,
}

impl RepositoryLinks {
    pub fn new() -> RepositoryLinks {
        RepositoryLinks {
            param_self: None,
            html: None,
            avatar: None,
            pullrequests: None,
            commits: None,
            forks: None,
            watchers: None,
            downloads: None,
            clone: None,
            hooks: None,
        }
    }
}

