/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubjectTypesRepository {
    #[serde(rename = "events", skip_serializing_if = "Option::is_none")]
    pub events: Option<Box<models::Link>>,
}

impl SubjectTypesRepository {
    pub fn new() -> SubjectTypesRepository {
        SubjectTypesRepository {
            events: None,
        }
    }
}

