/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TaskRawContent : task raw content
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TaskRawContent {
    /// The task contents
    #[serde(rename = "raw")]
    pub raw: String,
}

impl TaskRawContent {
    /// task raw content
    pub fn new(raw: String) -> TaskRawContent {
        TaskRawContent {
            raw,
        }
    }
}

